# Generated by Django 3.1.7 on 2021-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210405_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
    ]
