# Generated by Django 3.1.7 on 2021-04-15 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210410_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FO', 'Front Office'), ('RO', 'Reservation'), ('RT', 'Restaurant'), ('CL', 'Cleaning'), ('SR', 'Services'), ('WB', 'Website'), ('OT', 'Other')], max_length=2, verbose_name='Feedback Category')),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
