# Generated by Django 3.1.7 on 2021-04-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
