# Generated by Django 3.1.7 on 2021-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_img',
            field=models.ImageField(default='room_img/default.jpg', upload_to='room_img'),
        ),
    ]
