# Generated by Django 3.1.7 on 2021-04-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20210405_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
