# Generated by Django 3.1.7 on 2021-04-05 16:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20210405_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_img',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='room_img/default.jpg', force_format=None, keep_meta=True, quality=100, size=[800, 525], upload_to='room_img'),
        ),
    ]
