# Generated by Django 3.1.7 on 2021-04-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20210405_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('OCP', 'Occupied'), ('CLN', 'Clean'), ('AVA', 'Available'), ('OFF', 'Off')], default='AVA', max_length=3, verbose_name='Room Status'),
        ),
    ]
