# Generated by Django 3.1.7 on 2021-04-13 05:49

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200)),
                ('menu_description', ckeditor.fields.RichTextField()),
                ('menu_img', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='food_img/default.jpg', force_format=None, keep_meta=True, quality=100, size=[800, 525], upload_to='food_img')),
                ('menu_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
