# Generated by Django 3.1.7 on 2021-04-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='status',
            field=models.CharField(choices=[('AVA', 'Available'), ('OUT', 'Out of Stock')], default='AVA', max_length=3, verbose_name='Room Status'),
        ),
    ]
